//<auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

namespace Wfa.Console.Migrations
{
    public partial class addWikiaThumbnail : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "WikiaThumbnail",
                table: "Archwing",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "WikiaUrl",
                table: "Archwing",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "WikiaThumbnail",
                table: "Archwing");

            migrationBuilder.DropColumn(
                name: "WikiaUrl",
                table: "Archwing");
        }
    }
}
